class ProductData {
  // List of image URLs
  static final List<String> imageUrls = [
    "assets/images/product.jpeg",
    "assets/images/product1.jpeg",
    "assets/images/product2.jpeg",
    "assets/images/product3.jpeg",
    "assets/images/product4.jpeg",
    "assets/images/product5.jpeg",
    "assets/images/product6.jpeg",
    "assets/images/product7.jpeg",
    "assets/images/product8.jpeg",
    "assets/images/product9.jpeg",
    "assets/images/product10.jpeg",
    "assets/images/product11.jpeg",
    "assets/images/product12.jpeg",
    "assets/images/product13.jpeg",
    "assets/images/product14.jpeg",
    "assets/images/product15.jpeg",
    "assets/images/product16.jpeg",
    "assets/images/product17.jpeg",
    "assets/images/product18.jpeg",
    "assets/images/product19.jpeg",
  ];

  // List of product names
  static final List<String> productNames = [
    'Elegant Dress',
    'Stylish Shoes',
    'Luxury Handbag',
    'Summer Hat',
    'Silk Scarf',
    'Casual Shirt',
    'Denim Jeans',
    'Leather Jacket',
    'Gold Necklace',
    'Evening Gown',
    'Wool Sweater',
    'Sunglasses',
    'Formal Pants',
    'Sneakers',
    'Chic Blouse',
    'Cotton T-shirt',
    'Leather Belt',
    'Mini Skirt',
    'Designer Watch',
    'Bracelet',
  ];

  // List of brand names
  static final List<String> brandNames = [
    'Brand A',
    'Brand B',
    'Brand C',
    'Brand D',
    'Brand E',
    'Brand F',
    'Brand G',
    'Brand H',
    'Brand I',
    'Brand J',
    'Brand K',
    'Brand L',
    'Brand M',
    'Brand N',
    'Brand O',
    'Brand P',
    'Brand Q',
    'Brand R',
    'Brand S',
    'Brand T',
  ];

  // List of prices
  static final List<double> prices = [
    199.99,
    89.99,
    349.99,
    49.99,
    29.99,
    59.99,
    79.99,
    499.99,
    299.99,
    699.99,
    109.99,
    159.99,
    199.99,
    129.99,
    89.99,
    39.99,
    99.99,
    59.99,
    599.99,
    149.99,
  ];
}
