// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZOhDithURGIi-oX7ktQJlPA7_EULeiN0',
    appId: '1:325139347333:web:73706d40f71b2ae7aa76ec',
    messagingSenderId: '325139347333',
    projectId: 'e-commerce-7e6dd',
    authDomain: 'e-commerce-7e6dd.firebaseapp.com',
    storageBucket: 'e-commerce-7e6dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyyNRHU-GHIndPXn-yx_DZWRHDO-lsNxw',
    appId: '1:325139347333:android:b950f365d7ee7bcaaa76ec',
    messagingSenderId: '325139347333',
    projectId: 'e-commerce-7e6dd',
    storageBucket: 'e-commerce-7e6dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL2KF7iGt5C8pIJg-YJeS72SAAwHudEMc',
    appId: '1:325139347333:ios:d468ae17c9900267aa76ec',
    messagingSenderId: '325139347333',
    projectId: 'e-commerce-7e6dd',
    storageBucket: 'e-commerce-7e6dd.appspot.com',
    iosBundleId: 'com.example.whiteMatrixEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL2KF7iGt5C8pIJg-YJeS72SAAwHudEMc',
    appId: '1:325139347333:ios:7ee1777a5ac9e718aa76ec',
    messagingSenderId: '325139347333',
    projectId: 'e-commerce-7e6dd',
    storageBucket: 'e-commerce-7e6dd.appspot.com',
    iosBundleId: 'com.example.whiteMatrixEcommerce.RunnerTests',
  );
}
